openapi: '3.0.2'
info:
  title: LEAV
  version: '1.0'
servers:
  - url: /v1
  - url: https://editor.swagger.io/

paths:
  /videos:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Video'

components:
  schemas:
    Media:
      type: object
      properties:
        title:
          $ref: '#/components/schemas/Title'
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
    VideoMedia:
      allOf:
        - $ref: '#/components/schemas/Media'
        - type: object
          properties:
            Video:
              $ref: '#/components/schemas/Video'
    MusikCoverMedia:
      allOf:
        - $ref: '#/components/schemas/Media'
        - type: object
          properties:
            Song:
              $ref: '#/components/schemas/MusikMedia'
            Video:
              $ref: '#/components/schemas/Video'
    MusikMedia:
      allOf:
        - $ref: '#/components/schemas/Media'
        - type: object
          properties:
            Variants:
              type: array
              items: 
                $ref: '#/components/schemas/Video'
            Artists:
              type: array
              items:
                $ref: '#/components/schemas/Celebrity'
            CleanAudio:
              $ref: '#/components/schemas/Video'
            BestVideo:
              $ref: '#/components/schemas/Video'
    Video:
      type: object
      properties:
        title:
          $ref: '#/components/schemas/Title'
        formats:
          $ref: '#/components/schemas/Formats'
    Snippet:
      allOf:
        - $ref: '#/components/schemas/Video'
        - type: object
          properties:
            Parent:
              $ref: '#/components/schemas/Video'
            StartTime:
              type: integer
            Length:
              type: integer
    Formats:
      type: object
      properties:
        filename:
          type: string
        filesize:
          type: integer
        language:
          type: string
    Title:
      type: object
      properties:
        title: 
          type: string
        language:
          type: string
    Tag:
      type: object
    Celebrity:
      type: object
    Playlist:
      type: object
      properties:
        title:
          $ref: '#/components/schemas/Title'
        items:
          type: array
          items:
           $ref: '#/components/schemas/PlaylistItem'
    PlaylistItem:
      type: object
      properties:
        index:
          type: integer
        media:
          oneOf:
            - $ref: '#/components/schemas/MusikMedia'
            - $ref: '#/components/schemas/VideoMedia'
