/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"

	leav "github.com/lea-video/backend/go"
	leav_m "github.com/lea-video/backend/go/model"
)

func main() {
	// TODO: delete
	test()

	log.Printf("Server started")
	router := leav.NewRouter()
	log.Fatal(http.ListenAndServe(":8080", router))
}

func test() {
	leav.Initialise()

	fmt.Println("Marshal empty Playlist")
	p := leav_m.NewPlaylist(leav_m.NewTitle("Playlist 1"))
	b, err := json.Marshal(p)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(b))

	fmt.Println("Marshal Playlist with Song and Album")
	s := leav_m.NewSong(leav_m.NewTitle("Test Song"))
	s.AddCover(leav_m.NewCelebrity("Cover Artist"), leav_m.NewMedia(leav_m.NewTitle("Cover of Test Song")))
	p.AddItem(s)
	p.AddItem(leav_m.NewAlbum(leav_m.NewTitle("Test Album")))
	b, err = json.Marshal(p)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(b))

	fmt.Println("Unmarshal Playlist with Song and Album")
	var d leav_m.Playlist
	err = json.Unmarshal(b, &d)
	if err != nil {
		panic(err)
	}
	b, err = json.Marshal(d)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(b))
}
