/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

import (
	util "github.com/lea-video/backend/go/utility"
)

type RawSeries struct {
	ID string `json:"id,omitempty"`

	TitleID string `json:"titleID,omitempty"`

	SeasonIDs []string `json:"seasonIDs,omitempty"`
}

type Series struct {
	*RawSeries

	Title *Title `json:"title,omitempty"`

	Seasons []*Season `json:"seasons,omitempty"`
}

func NewSeries(title *Title) *Series {
	return &Series{
		RawSeries: &RawSeries{
			ID:        util.NewID(),
			TitleID:   title.getID(),
			SeasonIDs: make([]string, 0),
		},
		Title:   title,
		Seasons: make([]*Season, 0),
	}
}

func (s *Series) getID() string {
	return s.ID
}

func (*Series) getType() string {
	return "Series"
}
