/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

import (
	util "github.com/lea-video/backend/go/utility"
)

type RawImageSet struct {
	ID string `json:"id,omitempty"`

	TitleID string `json:"titleID,omitempty"`

	ImageIDs []string `json:"imageIDs,omitempty"`
}

type ImageSet struct {
	*RawImageSet

	Title *Title `json:"title,omitempty"`

	Images []*Media `json:"images,omitempty"`
}

func NewImageSet(title *Title) *ImageSet {
	return &ImageSet{
		RawImageSet: &RawImageSet{
			ID:       util.NewID(),
			TitleID:  title.getID(),
			ImageIDs: make([]string, 0),
		},
		Title:  title,
		Images: make([]*Media, 0),
	}
}

func (is *ImageSet) getID() string {
	return is.ID
}

func (*ImageSet) getType() string {
	return "ImageSet"
}
