/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type User struct {
	Id string `json:"id,omitempty"`

	Displayname string `json:"displayname,omitempty"`

	Email string `json:"email,omitempty"`

	Credentials []Credential `json:"credentials,omitempty"`
}
