/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

import (
	util "github.com/lea-video/backend/go/utility"
)

type Tag struct {
	ID string `json:"id,omitempty"`

	Title *Title `json:"Title,omitempty"`
}

func NewTag(title *Title) *Tag {
	return &Tag{
		ID:    util.NewID(),
		Title: title,
	}
}
