/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

import (
	util "github.com/lea-video/backend/go/utility"
)

type RawCelebrity struct {
	ID string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	TagIDs []string `json:"tagIDs,omitempty"`
}

type Celebrity struct {
	*RawCelebrity

	Tags []*Tag `json:"tags,omitempty"`
}

func NewCelebrity(name string) *Celebrity {
	return &Celebrity{
		RawCelebrity: &RawCelebrity{
			ID:     util.NewID(),
			Name:   name,
			TagIDs: make([]string, 0),
		},
		Tags: make([]*Tag, 0),
	}
}

func (c *Celebrity) getID() string {
	return c.ID
}
