/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

import (
	util "github.com/lea-video/backend/go/utility"
)

type RawMedia struct {
	ID string `json:"id,omitempty"`

	TitleID string `json:"titleID,omitempty"`

	TrackIDs []string `json:"trackIDs,omitempty"`

	TagIDs []string `json:"tagIDs,omitempty"`
}

type Media struct {
	*RawMedia

	Title *Title `json:"title,omitempty"`

	Tracks []*Track `json:"tracks,omitempty"`

	Tags []*Tag `json:"tags,omitempty"`
}

func NewMedia(title *Title) *Media {
	return &Media{
		RawMedia: &RawMedia{
			ID:       util.NewID(),
			TitleID:  title.getID(),
			TrackIDs: make([]string, 0),
			TagIDs:   make([]string, 0),
		},
		Title:  title,
		Tracks: make([]*Track, 0),
		Tags:   make([]*Tag, 0),
	}
}

func (m *Media) getID() string {
	return m.ID
}

func (*Media) getType() string {
	return "Media"
}
