/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

import (
	util "github.com/lea-video/backend/go/utility"
)

type Media struct {
	Id string `json:"id,omitempty"`

	Title *Title `json:"title,omitempty"`

	Tracks []*Track `json:"tracks,omitempty"`

	Tags []*Tag `json:"tags,omitempty"`
}

func NewMedia(title *Title) *Media {
	return &Media{
		Id:     util.NewID(),
		Title:  title,
		Tracks: make([]*Track, 0),
		Tags:   make([]*Tag, 0),
	}
}

func (m *Media) getID() string {
	return m.Id
}

func (*Media) getType() string {
	return "Media"
}
