/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

import (
	util "github.com/lea-video/backend/go/utility"
)

type Season struct {
	Id string `json:"id,omitempty"`

	Title *Title `json:"title,omitempty"`

	Series *Series `json:"series,omitempty"`

	Episode []*Media `json:"episode,omitempty"`
}

func (s *Series) NewSeason(title *Title) *Season {
	return &Season{
		Id:      util.NewID(),
		Title:   title,
		Series:  s,
		Episode: make([]*Media, 0),
	}
}

func (s *Season) getID() string {
	return s.Id
}

func (*Season) getType() string {
	return "Season"
}
