/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type Token struct {
	Token string `json:"token,omitempty"`
}

func (t *Token) isValid() bool {
	// TODO: implement
	return false
}

func (t *Token) getSession() *Session {
	// TODO: implement
	return nil
}
