/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

import (
	util "github.com/lea-video/backend/go/utility"
)

type Series struct {
	Id string `json:"id,omitempty"`

	Title *Title `json:"title,omitempty"`

	Seasons []*Season `json:"seasons,omitempty"`
}

func NewSeries(title *Title) *Series {
	return &Series{
		Id:      util.NewID(),
		Title:   title,
		Seasons: make([]*Season, 0),
	}
}

func (s *Series) getID() string {
	return s.Id
}

func (*Series) getType() string {
	return "Series"
}
