/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

import (
	util "github.com/lea-video/backend/go/utility"
)

type RawMovie struct {
	ID string `json:"id,omitempty"`

	TitleID string `json:"titleID,omitempty"`

	SequelID string `json:"sequelID,omitempty"`

	cutIDs []string `json:"cutIDs,omitempty"`
}

type Movie struct {
	*RawMovie

	Title *Title `json:"title,omitempty"`

	Sequel *Movie `json:"sequel,omitempty"`

	Cuts []*Media `json:"cuts,omitempty"`
}

func NewMovie(title *Title) *Movie {
	return &Movie{
		RawMovie: &RawMovie{
			ID:      util.NewID(),
			TitleID: title.getID(),
			cutIDs:  make([]string, 0),
		},
		Title: title,
		Cuts:  make([]*Media, 0),
	}
}

func (m *Movie) getID() string {
	return m.ID
}

func (*Movie) getType() string {
	return "Movie"
}
