/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

import "net/http"

type Password struct {
	Hash string `json:"hash,omitempty"`

	Salt string `json:"salt,omitempty"`
}

func (p *Password) isValid(r *http.Request) bool {
	// TODO: implement
	return false
}

func (p *Password) getSession(r *http.Request) *Session {
	// TODO: implement
	return nil
}
