/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

import (
	util "github.com/lea-video/backend/go/utility"
)

type ImageSet struct {
	Id string `json:"id,omitempty"`

	Title *Title `json:"title,omitempty"`

	Images []*Media `json:"images,omitempty"`
}

func NewImageSet(title *Title) *ImageSet {
	return &ImageSet{
		Id:     util.NewID(),
		Title:  title,
		Images: make([]*Media, 0),
	}
}

func (is *ImageSet) getID() string {
	return is.Id
}

func (*ImageSet) getType() string {
	return "ImageSet"
}
