/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

import (
	util "github.com/lea-video/backend/go/utility"
)

type RawAlbum struct {
	ID string `json:"id,omitempty"`

	TitleID string `json:"titleID,omitempty"`

	SongIDs []string `json:"songIDs,omitempty"`
}

type Album struct {
	*RawAlbum

	Title *Title `json:"title,omitempty"`

	Songs []*Song `json:"songs,omitempty"`
}

func NewAlbum(title *Title) *Album {
	return &Album{
		RawAlbum: &RawAlbum{
			ID:      util.NewID(),
			TitleID: title.getID(),
			SongIDs: make([]string, 0),
		},
		Title: title,
		Songs: make([]*Song, 0),
	}
}

func (a *Album) getID() string {
	return a.ID
}

func (*Album) getType() string {
	return "Album"
}
