/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

import (
	"encoding/json"

	util "github.com/lea-video/backend/go/utility"
)

type RawPlaylist struct {
	ID string `json:"id,omitempty"`

	TitleID string `json:"titleID,omitempty"`

	TagIDs []string `json:"tagIDs,omitempty"`

	ItemIDs []string `json:"itemIDs,omitempty"`
}

type Playlist struct {
	*RawPlaylist

	Title *Title `json:"title,omitempty"`

	Tags []*Tag `json:"tags,omitempty"`

	Items []*PlaylistItem `json:"items,omitempty"`
}

type RawPlaylistItem struct {
	ID string `json:"id,omitempty"`

	Index int32 `json:"index,omitempty"`

	RemovedAt int32 `json:"removedAt,omitempty"`

	AddedAt int32 `json:"addedAt,omitempty"`

	ItemID string `json:"itemID,omitempty"`
}

type PlaylistItem struct {
	*RawPlaylistItem

	Item Playable `json:"item,omitempty"`
}

type playlistItemJSON struct {
	ID string `json:"id,omitempty"`

	Index int32 `json:"index,omitempty"`

	RemovedAt int32 `json:"removedAt,omitempty"`

	AddedAt int32 `json:"addedAt,omitempty"`

	Item map[string]interface{} `json:"item,omitempty"`
}

func (p *PlaylistItem) MarshalJSON() ([]byte, error) {
	// Serialise PlaylistItem#Item
	tmp, err := json.Marshal(p.Item) // Convert to a json string
	if err != nil {
		return nil, err
	}
	var item map[string]interface{}
	err = json.Unmarshal(tmp, &item) // Convert to a map
	if err != nil {
		return nil, err
	}

	// Expand with type Keyword
	item["type"] = p.Item.getType()

	// Map to intermediate type
	data := playlistItemJSON{
		ID:        p.ID,
		Index:     p.Index,
		RemovedAt: p.RemovedAt,
		AddedAt:   p.AddedAt,
		Item:      item,
	}
	// return
	return json.Marshal(&data)
}

func (p *PlaylistItem) UnmarshalJSON(body []byte) error {
	data := playlistItemJSON{}
	err := json.Unmarshal(body, &data)
	if err != nil {
		return err
	}

	// Map to PlaylistItem
	p.RawPlaylistItem = &RawPlaylistItem{
		ID:        data.ID,
		Index:     data.Index,
		RemovedAt: data.RemovedAt,
		AddedAt:   data.AddedAt,
	}
	p.Item, err = UnmarshalPlayable(data.Item)

	return err
}

func NewPlaylist(title *Title) *Playlist {
	return &Playlist{
		RawPlaylist: &RawPlaylist{
			ID:      util.NewID(),
			TitleID: title.getID(),
			TagIDs:  make([]string, 0),
			ItemIDs: make([]string, 0),
		},
		Title: title,
		Tags:  make([]*Tag, 0),
		Items: make([]*PlaylistItem, 0),
	}
}

func (t *Playlist) AddItem(p Playable) {
	e := PlaylistItem{
		RawPlaylistItem: &RawPlaylistItem{
			ID:     util.NewID(),
			ItemID: p.getID(),
		},
		Item: p,
	}
	t.ItemIDs = append(t.ItemIDs, e.ID)
	t.Items = append(t.Items, &e)
}
