/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

import (
	util "github.com/lea-video/backend/go/utility"
)

type RawSeason struct {
	ID string `json:"id,omitempty"`

	TitleID string `json:"titleID,omitempty"`

	SeriesID string `json:"seriesID,omitempty"`

	EpisodeIDs []string `json:"episodeIDs,omitempty"`
}

type Season struct {
	*RawSeason

	Title *Title `json:"title,omitempty"`

	Series *Series `json:"series,omitempty"`

	Episode []*Media `json:"episode,omitempty"`
}

func (s *Series) NewSeason(title *Title) *Season {
	return &Season{
		RawSeason: &RawSeason{
			ID:         util.NewID(),
			TitleID:    title.getID(),
			SeriesID:   s.getID(),
			EpisodeIDs: make([]string, 0),
		},
		Title:   title,
		Series:  s,
		Episode: make([]*Media, 0),
	}
}

func (s *Season) getID() string {
	return s.ID
}

func (*Season) getType() string {
	return "Season"
}
