/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type RawSnippet struct {
	*RawMedia

	ParentID string `json:"parentID,omitempty"`

	Starttime int32 `json:"starttime,omitempty"`

	Length int32 `json:"length,omitempty"`
}

type Snippet struct {
	*Media
	*RawSnippet

	Parent *Media `json:"parent,omitempty"`
}

func (parent *Media) NewSnippet(title *Title, starttime, length int32) *Snippet {
	m := NewMedia(title)
	return &Snippet{
		RawSnippet: &RawSnippet{
			RawMedia:  m.RawMedia,
			ParentID:  parent.getID(),
			Starttime: starttime,
			Length:    length,
		},
		Media:  NewMedia(title),
		Parent: parent,
	}
}

func (snip *Snippet) NewSnippet(title *Title, starttime, length int32) *Snippet {
	m := NewMedia(title)
	return &Snippet{
		RawSnippet: &RawSnippet{
			RawMedia:  m.RawMedia,
			ParentID:  snip.Parent.getID(),
			Starttime: snip.Starttime + starttime,
			Length:    length,
		},
		Media:  NewMedia(title),
		Parent: snip.Parent,
	}
}

func (s *Snippet) getID() string {
	return s.Media.getID()
}

func (*Snippet) getType() string {
	return "Snippet"
}
