/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type Session struct {
	User *User `json:"user,omitempty"`

	IsDirectLogin bool `json:"isDirectLogin,omitempty"`
}
