/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package leav

type Series struct {
	Title *Title `json:"title,omitempty"`

	Seasons []*Season `json:"seasons,omitempty"`
}

func NewSeries(title *Title) *Series {
	return &Series{
		Title:   title,
		Seasons: make([]*Season, 0),
	}
}

func (*Series) getType() string {
	return "Series"
}
