/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package leav

type Season struct {
	Title *Title `json:"title,omitempty"`

	Series *Series `json:"series,omitempty"`

	Episode []*Media `json:"episode,omitempty"`
}

func (s *Series) NewSeason(title *Title) *Season {
	return &Season{
		Title:   title,
		Series:  s,
		Episode: make([]*Media, 0),
	}
}

func (*Season) getType() string {
	return "Season"
}
