/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Playlist struct {

	Id string `json:"id,omitempty"`

	Title *Title `json:"title,omitempty"`

	Tags *Tag `json:"tags,omitempty"`

	Items []PlaylistItem `json:"items,omitempty"`
}
