/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package leav

type Album struct {
	Title *Title `json:"title,omitempty"`

	Songs []*Song `json:"songs,omitempty"`
}

func NewAlbum(title *Title) *Album {
	return &Album{
		Title: title,
		Songs: make([]*Song, 0),
	}
}

func (*Album) getType() string {
	return "Album"
}
