/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package leav

type Media struct {
	Title *Title `json:"title,omitempty"`

	Tracks []*Track `json:"tracks,omitempty"`

	Tags []*Tag `json:"tags,omitempty"`
}

func NewMedia(title *Title) *Media {
	return &Media{
		Title:  title,
		Tracks: make([]*Track, 0),
		Tags:   make([]*Tag, 0),
	}
}

func (*Media) getType() string {
	return "Media"
}
