/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Media struct {

	Title *Title `json:"title,omitempty"`

	Tracks []Track `json:"tracks,omitempty"`

	Tags []Tag `json:"tags,omitempty"`
}
