/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package leav

type ImageSet struct {
	Title *Title `json:"title,omitempty"`

	Images []*Media `json:"images,omitempty"`
}

func NewImageSet(title *Title) *ImageSet {
	return &ImageSet{
		Title:  title,
		Images: make([]*Media, 0),
	}
}

func (*ImageSet) getType() string {
	return "ImageSet"
}
