/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package leav

type Snippet struct {
	*Media

	Parent *Media `json:"parent,omitempty"`

	Starttime int32 `json:"starttime,omitempty"`

	Length int32 `json:"length,omitempty"`
}

func (parent *Media) NewSnippet(title *Title, starttime, length int32) *Snippet {
	return &Snippet{
		Media:     NewMedia(title),
		Parent:    parent,
		Starttime: starttime,
		Length:    length,
	}
}

func (snip *Snippet) NewSnippet(title *Title, starttime, length int32) *Snippet {
	return &Snippet{
		Media:     NewMedia(title),
		Parent:    snip.Parent,
		Starttime: snip.Starttime + starttime,
		Length:    length,
	}
}

func (*Snippet) getType() string {
	return "Snippet"
}
