/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Celebrity struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Tags []Tag `json:"tags,omitempty"`
}
