/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Title struct {

	Id string `json:"id,omitempty"`

	Default_ *TitleDefault `json:"default,omitempty"`

	Other []TitleDefault `json:"other,omitempty"`
}
