/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package leav

type Movie struct {
	Title *Title `json:"title,omitempty"`

	Sequel *Movie `json:"sequel,omitempty"`

	Cuts []*Media `json:"cuts,omitempty"`
}

func NewMovie(title *Title) *Movie {
	return &Movie{
		Title: title,
		Cuts:  make([]*Media, 0),
	}
}

func (*Movie) getType() string {
	return "Movie"
}
