/*
 * LEAV
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utility

import (
	"errors"

	"github.com/bwmarrin/snowflake"
)

var node *snowflake.Node

func Init() {
	// Create a new Node with a Node number of 1
	var err error
	snowflake.Epoch = 1616161616161
	node, err = snowflake.NewNode(1)
	if err != nil {
		panic(err)
	}
}

func NewID() string {
	if node == nil {
		panic(errors.New("did not initialise snowflake"))
	}
	// Generate a snowflake ID.
	return node.Generate().String()
}
