openapi: '3.0.2'
info:
  title: LEAV
  version: '1.0'
servers:
  - url: /v1
  - url: https://editor.swagger.io/

paths:
  /user:
    get:
      responses:
        '200':
          description: Logged in User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '403':
          description: Not logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /user/login:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                error:
                  type: string
                result:
                  type: object
                  properties:
                    password:
                      type: string
                    username:
                      type: string
      responses:
        '200':
          description: Logged in User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: invalid error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /playlist:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Playlist'
  /playlist/{id}:
    get:
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: nice
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Playlist'

components:
  schemas:
# User
    User:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        displayname:
          type: string
        email:
          $ref: '#/components/schemas/EMail'
        credentials:
          type: array
          items:
            $ref: '#/components/schemas/Credential'
    Credential:
      oneOf:
        - $ref: '#/components/schemas/Password'
        - $ref: '#/components/schemas/Token'
    Session:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        isDirectLogin:
          type: boolean
    Password:
      type: object
      properties:
        hash:
          type: string
        salt:
          type: string
    Token:
      type: string
# General Stuff
    UUID:
      type: string
    EMail:
      type: string
    Track:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        filename:
          type: string
        filesize:
          type: integer
        language:
          type: string
        audioBitrate:
          type: integer
        audioEncoding:
          type: string
        videoBitrate:
          type: integer
        videoEncoding:
          type: string
    Title:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        default:
          type: string
        other:
          type: array
          items:
            type: object
            properties:
              title: 
                type: string
              language:
                type: string
    Tag:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        Title:
          $ref: '#/components/schemas/Title'
    Celebrity:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        name:
          type: string
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
# Media Types
    Media:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        title:
          $ref: '#/components/schemas/Title'
        tracks:
          type: array
          items:
            $ref: '#/components/schemas/Track'
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
    Snippet:
      allOf:
        - $ref: '#/components/schemas/Media'
        - type: object
          properties:
            parent:
              $ref: '#/components/schemas/Media'
            starttime:
              type: integer
            length:
              type: integer
    Series:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        title:
          $ref: '#/components/schemas/Title'
        seasons:
          type: array
          items:
            $ref: '#/components/schemas/Season'
    Season:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        title:
          $ref: '#/components/schemas/Title'
        series:
          $ref: '#/components/schemas/Series'
        episode:
          type: array
          items:
            $ref: '#/components/schemas/Media'
    Movie:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        title:
          $ref: '#/components/schemas/Title'
        sequel:
          $ref: '#/components/schemas/Movie'
        cuts:
          type: array
          items:
            $ref: '#/components/schemas/Media'
    Song:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        title:
          $ref: '#/components/schemas/Title'
        artists:
          type: array
          items:
            $ref: '#/components/schemas/Celebrity'
        featuring:
          type: array
          items:
            $ref: '#/components/schemas/Celebrity'
        variants:
          type: array
          items:
            $ref: '#/components/schemas/Media'
        covers:
          type: array
          items:
            type: object
            properties:
              artist:
                $ref: '#/components/schemas/Celebrity'
              cover:
                $ref: '#/components/schemas/Media'
        cleanAudio:
            $ref: '#/components/schemas/Media'
        defaultVideo:
            $ref: '#/components/schemas/Media'
    Album:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        title:
          $ref: '#/components/schemas/Title'
        songs:
          type: array
          items:
            $ref: '#/components/schemas/Song'
    ImageSet:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        title:
          $ref: '#/components/schemas/Title'
        images:
          type: array
          items:
            $ref: '#/components/schemas/Media'
# Playable Interface (All Media Types)
    Playable:
      allOf:
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/UUID'
        - oneOf:
          - $ref: '#/components/schemas/Series'
          - $ref: '#/components/schemas/Season'
          - $ref: '#/components/schemas/Movie'
          - $ref: '#/components/schemas/Song'
          - $ref: '#/components/schemas/Album'
          - $ref: '#/components/schemas/ImageSet'
          - $ref: '#/components/schemas/Media'
          - $ref: '#/components/schemas/Snippet'
# Playlist
    Playlist:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        title:
          $ref: '#/components/schemas/Title'
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        items:
          type: array
          items:
           $ref: '#/components/schemas/PlaylistItem'
    PlaylistItem:
      type: object
      properties:
        index:
          type: integer
        removedAt:
          type: integer
        addedAt:
          type: integer
        item:
           $ref: '#/components/schemas/Playable'
