name: Generate UML

on: [push, pull_request]

jobs:
  genUML:
    name: GenUML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'


      - name: install goplantuml
        run: |
          go get github.com/jfeliu007/goplantuml/parser
          go get github.com/jfeliu007/goplantuml/cmd/goplantuml

      - name: run goplantuml
        run: goplantuml -recursive -show-aggregations ./ > diagram.puml

      - name: Generate PNG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tpng diagram.puml

      - name: Archive diagram.png
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: diagram.png
